""":mod:`tender_intelligence.processing.docx` — DOCX extraction (prompt 09 §6).

WAHO publishes DOCX TORs (docs/06 §6.2), so DOCX is a first-class input. Extraction uses
python-docx, which reads the OOXML package directly — Word/Office is never required.
The document is read from bytes, so no temporary files are involved.

Structure: ``iter_inner_content()`` yields paragraphs and tables in true document order. The
separate ``.paragraphs`` and ``.tables`` collections do not preserve that interleaving, so a
deadline paragraph that follows an evaluation matrix would be indistinguishable from one that
precedes it. Each block becomes an :class:`ExtractedSection`, which is the "appropriate structural
representation" prompt 09 §8 requires in place of inventing fake PDF page numbers for a format
that has no pages.

Headings and metadata (prompt 12 §4)
------------------------------------
A heading is preserved as a paragraph that *reports* being a heading: each section carries the
Word style it was written in and, for the built-in ``Heading N`` styles, the level. This is the
format's own statement rather than an inference from font size or capitalisation, so it is recorded
as metadata on the block and the block's ``kind`` stays ``"paragraph"`` — a heading is still a
paragraph, and reclassifying it would misrepresent the document to every downstream consumer. The
package's core properties (title, author, subject, created/modified) are captured the same way:
useful, and never a substitute for text.

Merged cells: python-docx repeats a merged cell's text for each grid position it spans. That is
recorded as-is rather than de-duplicated, because collapsing spans would misreport the table's
true column structure.
"""

from __future__ import annotations

import io
import re
import zipfile
from dataclasses import dataclass, field

import docx
from docx.document import Document as DocxDocument
from docx.opc.exceptions import OpcError, PackageNotFoundError
from docx.table import Table
from docx.text.paragraph import Paragraph

from tender_intelligence.processing.errors import ParseFailedError
from tender_intelligence.processing.representation import ExtractedSection, ExtractedTable
from tender_intelligence.processing.tables import classify_table

_METHOD = "docx"

#: Word's built-in heading styles are named ``Heading 1`` … ``Heading 9`` in English builds and in
#: localized builds, so the level is parsed from the name rather than matched against a fixed list.
_HEADING_STYLE: re.Pattern[str] = re.compile(r"^Heading\s+(\d+)$", re.IGNORECASE)

#: Core properties preserved when present (prompt 12 §4). Bounded for the same reason PDF ``/Info``
#: values are: a title is a short string, and an unbounded one is a malformed document, not content.
#: ``comments`` is deliberately not kept: it is a free-text author note that template generators
#: pre-fill ("generated by ...", boilerplate) rather than metadata that identifies the document.
_CORE_PROPERTY_KEYS: tuple[str, ...] = ("title", "author", "subject", "keywords", "category")
_MAX_PROPERTY_CHARS = 512


def _heading_level(style_name: str | None) -> int | None:
    """The level of a built-in Word heading style, or ``None`` for ordinary styles."""
    if not style_name:
        return None
    match = _HEADING_STYLE.match(style_name.strip())
    if match is None:
        return None
    level = int(match.group(1))
    return level if 1 <= level <= 9 else None


def _style_name(paragraph: Paragraph) -> str | None:
    """The paragraph's style name, or ``None`` when the document declares none."""
    try:
        style = paragraph.style
        if style is None:
            return None
        name = style.name
    except Exception:  # a missing or malformed style part must not fail the document
        return None
    return str(name) if name else None


def _core_properties(document: DocxDocument) -> dict[str, str]:
    """The package's declared core properties, bounded and filtered (prompt 12 §4)."""
    try:
        properties = document.core_properties
    except Exception:  # core properties are optional; absence is normal
        return {}
    preserved: dict[str, str] = {}
    for key in _CORE_PROPERTY_KEYS:
        try:
            value = getattr(properties, key, None)
        except Exception:
            continue
        if not isinstance(value, str):
            continue
        cleaned = " ".join(value.split())
        if not cleaned:
            continue
        preserved[key] = (
            cleaned if len(cleaned) <= _MAX_PROPERTY_CHARS
            else cleaned[:_MAX_PROPERTY_CHARS] + " [truncated]"
        )
    return preserved


@dataclass(frozen=True)
class DocxExtractionResult:
    """Extracted DOCX content as ordered sections plus a flat table/reading-order view."""

    sections: list[ExtractedSection] = field(default_factory=list)
    tables: list[ExtractedTable] = field(default_factory=list)
    text: str = ""
    method: str = _METHOD
    metadata: dict[str, str] = field(default_factory=dict)


def _table_from_docx(table: Table, *, section_index: int, table_index: int) -> ExtractedTable:
    rows = [[cell.text.strip() for cell in row.cells] for row in table.rows]
    rows = [row for row in rows if any(row)]
    has_header = len(rows) > 1
    headers = list(rows[0]) if has_header else []
    role, role_source = classify_table(headers, rows)
    return ExtractedTable(
        location=f"section:{section_index}",
        index=table_index,
        headers=headers,
        rows=rows,
        header_convention="first_row" if has_header else "none",
        page=None,
        role=role,
        role_source=role_source,
    )


def extract_docx(data: bytes) -> DocxExtractionResult:
    """Extract *data* as a DOCX.

    Raises :class:`ParseFailedError` when the bytes are not a readable DOCX package.
    """
    try:
        document = docx.Document(io.BytesIO(data))
    except (
        zipfile.BadZipFile,
        PackageNotFoundError,
        OpcError,
        ValueError,
        KeyError,
    ) as exc:
        raise ParseFailedError(
            f"docx could not be parsed: {type(exc).__name__}",
            context={"format": "docx", "exception": type(exc).__name__},
        ) from exc

    sections: list[ExtractedSection] = []
    tables: list[ExtractedTable] = []
    parts: list[str] = []

    try:
        blocks = list(document.iter_inner_content())
    except Exception as exc:
        raise ParseFailedError(
            f"docx body could not be read: {type(exc).__name__}",
            context={"format": "docx", "exception": type(exc).__name__},
        ) from exc

    for index, block in enumerate(blocks):
        if isinstance(block, Paragraph):
            text = block.text.strip()
            if not text:
                continue
            style = _style_name(block)
            sections.append(
                ExtractedSection(
                    index=index,
                    kind="paragraph",
                    text=text,
                    style=style,
                    heading_level=_heading_level(style),
                )
            )
            parts.append(text)
            continue

        if isinstance(block, Table):
            table = _table_from_docx(block, section_index=index, table_index=len(tables))
            if not table.rows:
                continue
            tables.append(table)
            # The table's textual rendering is carried on its section so reading order is intact;
            # the structured rows remain available on both the section and the document.
            sections.append(
                ExtractedSection(
                    index=index, kind="table", text=table.to_text(), tables=[table]
                )
            )
            parts.append(table.to_text())

    return DocxExtractionResult(
        sections=sections,
        tables=tables,
        text="\n\n".join(parts).strip(),
        method=_METHOD,
        metadata=_core_properties(document),
    )
