"""New-listing detection / deduplication (prompt 05)."""

from tender_intelligence.dedup.classify import (
    ADDENDUM_ADDED,
    ADDENDUM_MARKER_KEY,
    CHANGE_MARKER_CHANGED,
    CHANGE_TYPE_BY_FIELD,
    COMPARISON_FIELDS,
    DEADLINE_CHANGED,
    NEW,
    OTHER_MATERIAL_CHANGE,
    TITLE_CHANGED,
    UNCHANGED,
    UPDATE,
    ChangePolicy,
    Comparison,
    compare,
    normalize_listing,
    normalize_tender,
)
from tender_intelligence.dedup.service import (
    COMPLETED,
    ERRORED,
    RUNNING,
    DedupError,
    DedupOutcome,
    DedupResult,
    DedupService,
    derive_run_status,
)

__all__ = [
    "ADDENDUM_ADDED",
    "ADDENDUM_MARKER_KEY",
    "CHANGE_MARKER_CHANGED",
    "CHANGE_TYPE_BY_FIELD",
    "COMPARISON_FIELDS",
    "COMPLETED",
    "DEADLINE_CHANGED",
    "DedupError",
    "DedupOutcome",
    "DedupResult",
    "DedupService",
    "ERRORED",
    "NEW",
    "OTHER_MATERIAL_CHANGE",
    "RUNNING",
    "TITLE_CHANGED",
    "UNCHANGED",
    "UPDATE",
    "ChangePolicy",
    "Comparison",
    "compare",
    "derive_run_status",
    "normalize_listing",
    "normalize_tender",
]
